config/routes.rb
Pinteresting::Application.routes.draw do
  resources :eavesdrops

  resources :microposts

  resources :pins

  devise_for :users
  resources :users do
  member do
      get :whoresponders, :whoinitiators, :conversations
    end
  end

  resources :relationships, only: [:create, :destroy]

  root "microposts#index"
  get "about" => "pages#about"
  get "conversations" => "pins#index"
  get "widgets" => "widgets#ilove"
  get "users_consulting" => "users#consulting_index"
  get "users_gradapplication" => "users#gradapplication_index"
  get "pins_consulting" => "pins#consulting_index"
  get "pins_gradapplication" => "pins#gradapplication_index"

  

end

app/models/eavesdrop.rb
class Eavesdrop < ActiveRecord::Base

	belongs_to :user;
	belongs_to :initiator, class_name: "User"
	belongs_to :responder, class_name: "User"
	belongs_to :pin;

	attr_accessible :user_id, :initiator_id, :responder_id
end

app/controllers/eavesdrops_controller.rb
class EavesdropsController < ApplicationController
  before_action :set_eavesdrop, only: [:show, :edit, :update, :destroy]

  # GET /eavesdrops
  # GET /eavesdrops.json
  def index
    @eavesdrops = Eavesdrop.all
  end

  # GET /eavesdrops/1
  # GET /eavesdrops/1.json
  def show
  end

  # GET /eavesdrops/new
  def new
    @eavesdrop = Eavesdrop.new
  end

  # GET /eavesdrops/1/edit
  def edit
  end

  # POST /eavesdrops
  # POST /eavesdrops.json

  #@user = User.find(params[:relationship][:responder_id])

  def create
    @eavesdrop = Eavesdrop.new(eavesdrop_params)
    #@pin = Pin.find([:eavesdrop][:initiator_id][:responder_id])
    #@pin = Pin.where("initiator_id = (?) AND responder_id = (?)", @eavesdrop.initiator_id, @eavesdrop.responder_id)
    #where("user_id IN (?) OR user_id = ?", responder_user_ids, user)

    respond_to do |format|
      if @eavesdrop.save
        #flash[:notice] = "You are now eavesdropping on this conversation"
        format.html { redirect_to root_url, notice: 'You are now eavesdropping on this conversation' }
        #format.html { redirect_to @eavesdrop.user, notice: 'You are now eavesdropping on this conversation' }
        #format.html { redirect_to url_for(:controller => :pins, :action => :show), notice: 'You are now eavesdropping on this conversation' }
        format.json { render action: 'show', status: :created, location: @eavesdrop }
      else
        #format.html { redirect_to @pin }
        format.html { render action: 'new' }
        format.json { render json: @eavesdrop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eavesdrops/1
  # PATCH/PUT /eavesdrops/1.json
  def update
    respond_to do |format|
      if @eavesdrop.update(eavesdrop_params)
        #format.html { redirect_to @pin, notice: 'You are now eavesdropping on this conversation' }
        format.html { redirect_to @eavesdrop, notice: 'Eavesdrop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to root_url }
        #format.html { render action: 'edit' }
        format.json { render json: @eavesdrop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eavesdrops/1
  # DELETE /eavesdrops/1.json
  def destroy
    @eavesdrop.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'You are no long eavesdropping on the conversation'  }
      #format.html { redirect_to @eavesdrop.user }
      #format.html { redirect_to eavesdrops_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eavesdrop
      @eavesdrop = Eavesdrop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def eavesdrop_params
      params.require(:eavesdrop).permit(:user_id, :initiator_id, :responder_id)
    end
end

app/helpers/eavesdrops_helper.rb
module EavesdropsHelper
end

app/views/eavesdrops/_form.html.erb
<%= form_for(@eavesdrop) do |f| %>
  <% if @eavesdrop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@eavesdrop.errors.count, "error") %> prohibited this eavesdrop from being saved:</h2>

      <ul>
      <% @eavesdrop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :initiator_id %><br>
    <%= f.number_field :initiator_id %>
  </div>
  <div class="field">
    <%= f.label :responder_id %><br>
    <%= f.number_field :responder_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eavesdrops/edit.html.erb
<h1>Editing eavesdrop</h1>

<%= render 'form' %>

<%= link_to 'Show', @eavesdrop %> |
<%= link_to 'Back', eavesdrops_path %>

app/views/eavesdrops/index.html.erb
<h1>Listing eavesdrops</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Initiator</th>
      <th>Responder</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @eavesdrops.each do |eavesdrop| %>
      <tr>
        <td><%= eavesdrop.user_id %></td>
        <td><%= eavesdrop.initiator_id %></td>
        <td><%= eavesdrop.responder_id %></td>
        <td><%= link_to 'Show', eavesdrop %></td>
        <td><%= link_to 'Edit', edit_eavesdrop_path(eavesdrop) %></td>
        <td><%= link_to 'Destroy', eavesdrop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Eavesdrop', new_eavesdrop_path %>

app/views/eavesdrops/new.html.erb
<h1>New eavesdrop</h1>

<%= render 'form' %>

<%= link_to 'Back', eavesdrops_path %>

app/views/eavesdrops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @eavesdrop.user_id %>
</p>

<p>
  <strong>Initiator:</strong>
  <%= @eavesdrop.initiator_id %>
</p>

<p>
  <strong>Responder:</strong>
  <%= @eavesdrop.responder_id %>
</p>

<%= link_to 'Edit', edit_eavesdrop_path(@eavesdrop) %> |
<%= link_to 'Back', eavesdrops_path %>