config/routes.rb
Pinteresting::Application.routes.draw do
  resources :eavesdrops

  resources :microposts

  resources :pins

  devise_for :users
  resources :users do
  member do
      get :whoresponders, :whoinitiators, :conversations
    end
  end

  resources :relationships, only: [:create, :destroy]

  root "microposts#index"
  get "about" => "pages#about"
  get "conversations" => "pins#index"
  get "widgets" => "widgets#ilove"
  get "users_consulting" => "users#consulting_index"
  get "users_gradapplication" => "users#gradapplication_index"
  get "pins_consulting" => "pins#consulting_index"
  get "pins_gradapplication" => "pins#gradapplication_index"

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user;
	belongs_to :relationship;
	belongs_to :initiator, class_name: "User"
	belongs_to :responder, class_name: "User"
	has_many :eavesdrops;

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "50x50>", :profile => "150x150>"}, :default_url => 'default_gravatar.jpeg'
	default_scope -> { order('updated_at DESC') }
	#validates :image, presence: true
	validates :description, presence: true
	attr_accessible :description, :user_id, :initiator_id, :responder_id
	searchable do
		text :description
		time :created_at
		# :message1, :message2, :message3, :message4, :message5, :message6
		#, :name
	end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    #@pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    @search = Pin.search do
    fulltext params[:search]
    #phrase_slop 1
    #with(:published_at).less_than(Time.zone.now)
    #with(:publish_month, params[:month]) if params[:month].present?
    order_by :created_at, :desc
    end
    @pins = @search.results
    #@conversation_items = @pin.initiator.conversation_list(@pin.initiator, @pin.responder)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @conversation_items = @pin.initiator.conversation_list(@pin.initiator, @pin.responder).paginate(page: params[:page], :per_page => 10)
  end

  # GET /pins/new
  def new
    # @pin = Pin.new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  def consulting_index
    @consulting_pins = Pin.where("category = (?)",1).paginate(page: params[:page], :per_page => 30)
  end

  def gradapplication_index
    @gradapplication_pins = Pin.where("category = (?)",2).paginate(page: params[:page], :per_page => 30)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_eavesdrop.html.erb
<%= form_for(current_user.eavesdrops.build(user_id: current_user.id, initiator_id: @pin.initiator.id, responder_id: @pin.responder.id)) do |f| %>
  <div><%= f.hidden_field :user_id %></div>
  <div><%= f.hidden_field :initiator_id %></div>
  <div><%= f.hidden_field :responder_id %></div>
  <%= f.submit "Eavesdrop", class: "btn btn-large btn-primary" %>
<% end %>

app/views/pins/_eavesdrop_form.html.erb
<% unless current_user?(@user) %>
  <div id="eavesdrop_form">
	  <% if current_user.eavesdropping?(current_user, @pin.initiator, @pin.responder) %>
	    <%= render 'pins/uneavesdrop' %>
	  <% else %>
	    <%= render 'pins/eavesdrop' %>
	  <% end %>
  </div>
<% end %>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/pins/_index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<% if user_signed_in? %>
  <%= render 'search' %><p></p>
<% end %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <!--<div class="box panel panel-default"> -->
    <div class=" pin-box panel panel-default center">

      <div class="panel-body">
        <% if false %>  <p>Topic: <%= link_to pin.description, pin %></p> <% end %>
        Topic: <%= link_to pin.description, pin %>
        <% if false %>
          <p><%= pin.message1 %></p>
          <p><%= pin.message2 %></p>
          <p><%= pin.message3 %></p>
          <p><%= pin.message4 %></p>
          <p><%= pin.message5 %></p>
          <p><%= pin.message6 %></p>
        <% end %>
        <% if false %> <p><strong><%= pin.user.name if pin.user %></strong></p> <% end %>
        <% if current_user && (pin.user == current_user) %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>Delete
            <% end %>
          </div>
        <% end %>
      </div>


      <div class="gravatar-wide good-sharpborder">
      <% if user_signed_in? %>
        <%= image_tag(pin.initiator.image.url(:thumb)) %><p></p>
        <%= link_to pin.initiator.name,pin.initiator %>
      <% else %>
        <%= image_tag(pin.initiator.image.url(:thumb)) %><p></p>
        <%= link_to pin.initiator.name,root_path %>
      <% end %>
      </div>

      <div class="gravatar-wide good-sharpborder">
      <% if user_signed_in? %> 
        <%= image_tag(pin.responder.image.url(:thumb)) %><p></p>
        <%= link_to pin.responder.name,pin.responder %>
      <% else %>
        <%= image_tag(pin.responder.image.url(:thumb)) %><p></p>
        <%= link_to pin.responder.name,root_path %>
      <% end %>
      </div>

      
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/_uneavesdrop.html.erb
<%= form_for(current_user.eavesdrops.find_by(user_id: current_user.id, initiator_id: @pin.initiator_id, responder_id: @pin.responder_id), html: { method: :delete }) do |f| %>
  <%= f.submit "Uneavesdrop", class: "btn btn-large  btn-primary" %>
<% end %>

app/views/pins/consulting_index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<% if user_signed_in? %>
  <%= render 'search' %><p></p>
<% end %>

<div id="pins" class="transitions-enabled">
  <% @consulting_pins.each do |pin| %>
    <!--<div class="box panel panel-default"> -->
    <div class=" pin-box panel panel-default center">

      <div class="panel-body">
        <% if false %>  <p>Topic: <%= link_to pin.description, pin %></p> <% end %>
        Topic: <%= link_to pin.description, pin %>
        <% if false %>
          <p><%= pin.message1 %></p>
          <p><%= pin.message2 %></p>
          <p><%= pin.message3 %></p>
          <p><%= pin.message4 %></p>
          <p><%= pin.message5 %></p>
          <p><%= pin.message6 %></p>
        <% end %>
        <% if false %> <p><strong><%= pin.user.name if pin.user %></strong></p> <% end %>
        <% if current_user && (pin.user == current_user) %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>Delete
            <% end %>
          </div>
        <% end %>
      </div>


      <div class="gravatar-wide good-sharpborder">
      <% if user_signed_in? %>
        <%= image_tag(pin.initiator.image.url(:thumb)) %><p></p>
        <%= link_to pin.initiator.name,pin.initiator %>
      <% else %>
        <%= image_tag(pin.initiator.image.url(:thumb)) %><p></p>
        <%= link_to pin.initiator.name,root_path %>
      <% end %>
      </div>

      <div class="gravatar-wide good-sharpborder">
      <% if user_signed_in? %> 
        <%= image_tag(pin.responder.image.url(:thumb)) %><p></p>
        <%= link_to pin.responder.name,pin.responder %>
      <% else %>
        <%= image_tag(pin.responder.image.url(:thumb)) %><p></p>
        <%= link_to pin.responder.name,root_path %>
      <% end %>
      </div>

      
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @consulting_pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/gradapplication_index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<% if user_signed_in? %>
  <%= render 'search' %><p></p>
<% end %>

<div id="pins" class="transitions-enabled">
  <% @gradapplication_pins.each do |pin| %>
    <!--<div class="box panel panel-default"> -->
    <div class=" pin-box panel panel-default center">

      <div class="panel-body">
        <% if false %>  <p>Topic: <%= link_to pin.description, pin %></p> <% end %>
        Topic: <%= link_to pin.description, pin %>
        <% if false %>
          <p><%= pin.message1 %></p>
          <p><%= pin.message2 %></p>
          <p><%= pin.message3 %></p>
          <p><%= pin.message4 %></p>
          <p><%= pin.message5 %></p>
          <p><%= pin.message6 %></p>
        <% end %>
        <% if false %> <p><strong><%= pin.user.name if pin.user %></strong></p> <% end %>
        <% if current_user && (pin.user == current_user) %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>Delete
            <% end %>
          </div>
        <% end %>
      </div>


      <div class="gravatar-wide good-sharpborder">
      <% if user_signed_in? %>
        <%= image_tag(pin.initiator.image.url(:thumb)) %><p></p>
        <%= link_to pin.initiator.name,pin.initiator %>
      <% else %>
        <%= image_tag(pin.initiator.image.url(:thumb)) %><p></p>
        <%= link_to pin.initiator.name,root_path %>
      <% end %>
      </div>

      <div class="gravatar-wide good-sharpborder">
      <% if user_signed_in? %> 
        <%= image_tag(pin.responder.image.url(:thumb)) %><p></p>
        <%= link_to pin.responder.name,pin.responder %>
      <% else %>
        <%= image_tag(pin.responder.image.url(:thumb)) %><p></p>
        <%= link_to pin.responder.name,root_path %>
      <% end %>
      </div>

      
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @gradapplication_pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<% if user_signed_in? %>
  <%= render 'search' %><p></p>
<% end %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <!--<div class="box panel panel-default"> -->
    <div class=" pin-box panel panel-default center">

      <div class="panel-body">
        <% if false %>  <p>Topic: <%= link_to pin.description, pin %></p> <% end %>
        Topic: <%= link_to pin.description, pin %>
        <% if false %>
          <p><%= pin.message1 %></p>
          <p><%= pin.message2 %></p>
          <p><%= pin.message3 %></p>
          <p><%= pin.message4 %></p>
          <p><%= pin.message5 %></p>
          <p><%= pin.message6 %></p>
        <% end %>
        <% if false %> <p><strong><%= pin.user.name if pin.user %></strong></p> <% end %>
        <% if current_user && (pin.user == current_user) %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>Delete
            <% end %>
          </div>
        <% end %>
      </div>


      <div class="gravatar-wide good-sharpborder">
      <% if user_signed_in? %>
        <%= image_tag(pin.initiator.image.url(:thumb)) %><p></p>
        <%= link_to pin.initiator.name,pin.initiator %>
      <% else %>
        <%= image_tag(pin.initiator.image.url(:thumb)) %><p></p>
        <%= link_to pin.initiator.name,root_path %>
      <% end %>
      </div>

      <div class="gravatar-wide good-sharpborder">
      <% if user_signed_in? %> 
        <%= image_tag(pin.responder.image.url(:thumb)) %><p></p>
        <%= link_to pin.responder.name,pin.responder %>
      <% else %>
        <%= image_tag(pin.responder.image.url(:thumb)) %><p></p>
        <%= link_to pin.responder.name,root_path %>
      <% end %>
      </div>

      
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<!--
<link rel="stylesheet" href="social-likes_classic.css">
<script src="jquery.min.js"></script>
<script src="social-likes.min.js"></script>
-->
<% if user_signed_in? %>
	<%= link_to 'Eavesdrop on other conversations', pins_path %>
<% else %>
	<%= link_to 'Check out other conversations like this by signing up. Click here', root_path %>
<% end %>
<%#= link_to 'Eavesdrop on other conversations', pins_path %>
<%#= @pin.responder.name %>

<div class="row">
	<div class="col-md-offset-2 col-md-8 light-gray-background">
		
		<div class="center col-md-6">
			<%= image_tag @pin.initiator.image.url(:profile) %>	
			<% if user_signed_in? %>
				<h3><%= link_to @pin.initiator.name, @pin.initiator %></h3>
			<% else %>
				<h3><%= link_to @pin.initiator.name, root_path %></h3>
			<% end %>
		</div>
		<div class="center col-md-6">
			<%= image_tag @pin.responder.image.url(:profile) %>	
			<% if user_signed_in? %>
				<h3><%= link_to @pin.responder.name, @pin.responder %></h3>
			<% else %>
				<h3><%= link_to @pin.responder.name, root_path %></h3>
			<% end %>
		</div>
	</div>
</div>
<p></p>

<% if false %>
	<div class="row">
		<div class="col-md-offset-2 col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading center">
					<%= image_tag @pin.image.url(:medium) %>	
				</div>

				<% if false %>
				<div class="panel-body">
					<p><%= @pin.description %></p>
	        <p><%= @pin.message1 %></p>
	        <p><%= @pin.message2 %></p>
	        <p><%= @pin.message3 %></p>
	        <p><%= @pin.message4 %></p>
	        <p><%= @pin.message5 %></p>
	        <p><%= @pin.message6 %></p>
					<p><strong><%= @pin.user.name if @pin.user %></strong></p>
					<% if @pin.user == current_user %>
						<%= link_to edit_pin_path(@pin) do %>
	            <span class="glyphicon glyphicon-edit"></span>Edit
	          <% end %>
					<% end %> 
				</div>
				<% end %>
			</div>
		</div>
	</div>
<% end %>
<%# @conversation_items = @pin.initiator.conversation_list(@pin.initiator, @pin.responder) %>
<%# This is to list out the conversation between users %>
<section>
  <%#= render 'users/conversation', :collection => @conversation_items %>
</section>

<section class="row">

	<div class="col-md-offset-2 col-md-8 good-border light-gray-background">

		<aside >
			<section>
		    <h1 class="center">Conversation between <%= @pin.responder.name %> and <%= @pin.initiator.name %> on <font color="#c0392b"><%=@pin.description %></font>
		    <p></p> 
		    <%= render 'pins/eavesdrop_form' %>
		    <p></p>
		    <div class="social-likes" data-url=<%= request.original_url %> data-title="Check out my conversation on OneDegree...">
					<div class="facebook" title="Share link on Facebook">Facebook</div>
					<div class="twitter" title="Share link on Twitter">Twitter</div>
					<div class="plusone" title="Share link on Google+">Google+</div>
				</div> 
		    </h1>
	    </section>
	  </aside>
  	<%= render 'users/conversation', :collection => @conversation_items %>
  </div>
</section>


<div class="span8">
  <%#= render 'microposts/communicate_form' %>
</div>