config/routes.rb
Pinteresting::Application.routes.draw do
  resources :eavesdrops

  resources :microposts

  resources :pins

  devise_for :users
  resources :users do
  member do
      get :whoresponders, :whoinitiators, :conversations
    end
  end

  resources :relationships, only: [:create, :destroy]

  root "microposts#index"
  get "about" => "pages#about"
  get "conversations" => "pins#index"
  get "widgets" => "widgets#ilove"
  get "users_consulting" => "users#consulting_index"
  get "users_gradapplication" => "users#gradapplication_index"
  get "pins_consulting" => "pins#consulting_index"
  get "pins_gradapplication" => "pins#gradapplication_index"

  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user

  #belongs_to :initiator, class_name: "User"
  #belongs_to :responder, class_name: "User"

	default_scope -> { order('created_at DESC') }
	validates :content, length: { maximum: 15000 }
	#validates :user_id, presence: true

  attr_accessible :content, :user_id, :initiator, :responder, :topic

	def self.from_users_responded_by(user)
    #responder_user_ids = user.responder_user_ids
    #where("user_id IN (?) OR user_id = ?", responder_user_ids, user)

    responder_user_ids = "SELECT responder_id FROM relationships WHERE initiator_id = :user_id"
    where("user_id IN (#{responder_user_ids}) OR user_id = :user_id", user_id: user.id)
  end

  #this function is not needed. should be deleted
  def self.from_certain_user(user)
    responder_user_ids = user.id
    where("user_id IN (?) OR user_id = ?", responder_user_ids, user)

    #responder_user_ids = user.id
  end

  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    #@microposts = Micropost.where("user_id = ?", id)
    #@user = User.find(params[:id])
    #@microposts = @user.microposts.paginate(:page => params[:page], :per_page => 5)
    @microposts = Micropost.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    #@pin = Pin.where("initiator_id = (?) AND responder_id = (?)", @eavesdrop.initiator_id, @eavesdrop.responder_id)
    if signed_in?
      @micropost = current_user.microposts.build if signed_in?
      #@feed_items = current_user.feed.paginate(page: params[:page], :per_page => 10)
      @feed_items = Micropost.where("initiator = (?) OR responder = (?)", current_user, current_user).paginate(page: params[:page], :per_page => 10)
      @eavesdrop_items = current_user.eavesdrops
      @eavesdrop_recommend_items = current_user.eaveslist_recommend
      #@pins = current_user.eaveslist(@eavesdrop_items)
    end
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 25)
  end



  # GET /microposts/1
  # GET /microposts/1.json
  def show
    #@user = User.find(params[:id])
    #@microposts = @user.microposts.paginate(page: params[:page])
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end


  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)
    #debugger
    respond_to do |format|
      if @micropost.save
        format.html { redirect_to root_url, notice: 'Thanks for posting! You will be notified as soon as you receive a response' }
        @micropost.responder.inspect
        format.json { render action: 'show', status: :created, location: @micropost }
        #flash[:success] = "Micropost created!"
        #redirect_to root_url
      
        #if (@micropost.topic == nil or @micropost.topic == "")
        #else
          #current_user.communicate!(User.find_by_id(@micropost.responder))
        #end
        #other_user = User.find_by_id(@micropost.responder)
        if (current_user.first_communicating?(User.find_by_id(@micropost.responder)) or User.find_by_id(@micropost.responder).first_communicating?(current_user))
        #if current_user.communicating?(current_user, User.find_by_id(@micropost.responder))
        #if (current_user.communicating?(current_user, User.find_by_id(@micropost.responder)) or User.find_by_id(@micropost.responder).communicating?(current_user, User.find_by_id(@micropost.responder)))
        else
          current_user.communicate!(User.find_by_id(@micropost.responder))
          Pin.create(:description => @micropost.topic, :responder_id => @micropost.responder, :initiator_id => @micropost.initiator, :category => @micropost.category)
        end

      else
        format.html { render action: root_url }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
        @feed_items = []
      end

    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id, :initiator, :responder, :topic)
    end

    
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_communicate.html.erb
<%= form_for(current_user.relationships.build(responder_id: @user.id)) do |f| %>
  <div><% f.hidden_field :responder_id %></div>
  <%= f.submit "communicate", class: "btn btn-large btn-primary" %>
<% end %>

app/views/microposts/_communicate_form.html.erb
<% unless current_user?(@user) %>
  <div id="communicate_form">
	  <% if current_user.communicating?(current_user, @user) %>
	    <%= render 'microposts/uncommunicate' %>
	  <% else %>
	    <%= render 'microposts/communicate' %>
	  <% end %>
  </div>
<% end %>

app/views/microposts/_eavesdrop_item.html.erb
<li id="<%= eavesdrop_item.id %>">
  <%#= link_to gravatar_for(feed_item.user), feed_item.user %>
  <%#= eavesdrop_item.id %>
  <%# @pins = Pin.where("initiator_id = (?) AND responder_id = (?)", eavesdrop_item.initiator_id, eavesdrop_item.responder_id) %>
  <% @pins = current_user.eaveslist(eavesdrop_item) %>
  <%#= @pins.count %>

 	<% @pins.each do |pin| %>
 	  <span class="content">
	    <%= link_to pin.description, pin %>
  	</span>
	  <span class="timestamp">
	    Updated <%= time_ago_in_words(pin.updated_at) %> ago.
	  </span>
	<% end %>
</li>

  <%#= link_to eavesdrop_item.user.name, conversation_item.user %>

app/views/microposts/_eavesdrop_list.html.erb
<% if @eavesdrop_items.any? %>
<%#= @eavesdrop_items.count %>
	<aside>
		<section>
      <h1>Conversations you are eavesdropping</h1> 
    </section>
  </aside>
  <ol class="microposts">
    <%= render partial: 'eavesdrop_item', collection: @eavesdrop_items %>
  </ol>
  <%#= will_paginate @eavesdrop_items, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/microposts/_eavesdrop_recommend_item.html.erb
<li id="<%#= eavesdrop_recommend_item.id %>">
  <%#= link_to gravatar_for(feed_item.user), feed_item.user %>
  <%#= eavesdrop_item.id %>
  <%# @pins = Pin.where("initiator_id = (?) AND responder_id = (?)", eavesdrop_item.initiator_id, eavesdrop_item.responder_id) %>
  <% @pins = current_user.eaveslist_recommend() %>
  <%#= @pins.count %>
 	<% @pins.each do |pin| %>
 	  <span class="content">
	    <%= link_to pin.description, pin %>
  	</span>
    <span class="timestamp">
      <% if false %> Updated <%= time_ago_in_words(pin.updated_at) %> ago. <% end %>
      With <%= User.find(pin.responder_id).name %>
    </span>
    <!--
	  <span class="timestamp">
	    Updated <%= time_ago_in_words(pin.updated_at) %> ago.
	  </span>
    -->
	<% end %>
</li>

  <%#= link_to eavesdrop_item.user.name, conversation_item.user %>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :initiator %><br>
    <%= f.number_field :initiator %>
  </div>
  <div class="field">
    <%= f.label :responder %><br>
    <%= f.number_field :responder %>
  </div>
  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/microposts/_micropost_form.html.erb
<%#= form_for(@micropost) do |f| %>

<%= form_for(current_user.microposts.build(user_id: @user.id)) do |f| %>
  <%#= render 'shared/error_messages', object: f.object %>
  <div><%= f.hidden_field :user_id %></div>
  <div class="field">
  	<div>
    	<%= f.text_area :content, placeholder: "Compose new micropost...", class: "big-text-field" %>
    </div>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/microposts/_uncommunicate.html.erb
<%#= current_user.id %>
<%#= form_for(current_user.relationships.find_by(responder_id: @user), html: { method: :delete }) do |f| %>
  <div><%#= f.hidden_field :responder_id %></div>
  <%#= f.submit "uncommunicate", class: "btn btn-large btn-primary", confirm: "Are you sure. This will terminate the conversation" %>
<%# end %>

<%#= form_for(Relationship.where("(initiator_id = (?) and responder_id = (?)) or (initiator_id = (?) and responder_id = (?))", current_user.id, @user.id, @user.id, current_user.id), html: { method: :delete }) do |f| %>

<%#= form_for(current_user.relationships, html: { method: :delete }) do |f| %>

<%#= form_for(Relationship.where("initiator_id = ?",@user.id), html: { method: :delete }) do |f| %>
<% if false %>
	<% if @user.relationships.find_by(responder_id: current_user) %>
	<%= current_user.id %>
		<%= form_for(@user.relationships.find_by(responder_id: current_user), html: { method: :delete }) do |f| %>
		<div><% f.hidden_field :responder_id %></div>
	  <%= f.submit "End Communication", class: "btn btn-large btn-primary", confirm: "Are you sure. This will terminate the conversation with this user" %>
		<% end %>

	<% elsif current_user.relationships.find_by(responder_id: @user) %>
	<%= @user.id %>
	  <%= form_for(current_user.relationships.find_by(responder_id: @user), html: { method: :delete }) do |f| %>
	  <div><% f.hidden_field :responder_id %></div>
	  <%= f.submit "End Communication", class: "btn btn-large btn-primary", confirm: "Are you sure. This will terminate the conversation with this user" %>
	  <% end %>
	<% end %>
<% end %>

<% if @user.relationships.find_by(responder_id: current_user) %>
<% current_user.id %>
	<%= form_for(@user.relationships.find_by(responder_id: current_user, initiator_id: @user), html: { method: :delete }) do |f| %>
	<div><% f.hidden_field :responder_id %></div>
	<div><% f.hidden_field :initiator_id %></div>
  <%= f.submit "End Communication", class: "btn btn-large btn-primary", confirm: "Are you sure. This will terminate the conversation with this user" %>
	<% end %>

<% elsif current_user.relationships.find_by(responder_id: @user) %>
<% @user.id %>
  <%= form_for(current_user.relationships.find_by(responder_id: @user, initiator_id: current_user), html: { method: :delete }) do |f| %>
  <div><% f.hidden_field :responder_id %></div>
  <div><% f.hidden_field :initiator_id %></div>
  <%= f.submit "End Communication", class: "btn btn-large btn-primary", confirm: "Are you sure. This will terminate the conversation with this user" %>
  <% end %>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<% render 'pages/stats' if user_signed_in? %>

<% if signed_in? %>
  <div class="row">
    <aside class="col-md-3">
      <section>
        <%= render 'user_info' %>
      </section>
      <!--
      <section>
        <%#= render 'micropost_form' %>
      </section>
      -->
      <section>
        <%= render 'users/search' %>
      </section>

      <% if @eavesdrop_items.any? %>
        <div class="good-border">
          <%= render 'eavesdrop_list' %>
        </div>
      <% else %>
        <div class="good-border">
          <section>
            <h1>You are not eavesdropping on any conversations. Check out a few recommendations below...</h1> 
          </section>
        </div>  
      <% end %>

      <p></p>
      <% if @eavesdrop_recommend_items.any? %>
        <div class="good-border">
          <%= render 'eavesdrop_recommend_list' %>
        </div>
      <% else %>
        <div class="good-border">
          <section>
            <h1>Currently, there are no recommendations for you to eavesdrop</h1> 
          </section>
        </div>  
      <% end %>

    </aside>
  



    <div class="col-md-1"></div>
      <div class="col-md-8 good-border light-gray-background">
        <% if @feed_items.any? %>  
          <%= render 'feed' %>
        <% else %>
          <aside>
            <section>
              <h1>Welcome! Do the following to get started...</h1><p></p>
              <ul>
                <!--
                <li><h5>You can search for other people by their interests or location to talk to <em>(to the left)</em></h5></li> -->
                <li><h5>Click on 'Conversations' above to check out conversations other users are having <em></em></h5></li>
                <li><h5>Click on 'Featured Users', click on anyone's profile and ask them any question you want advice on or help with. Really just ask <em></em></h5></li>
                <!--<li><h5>You can eavesdrop on recommended conversations <em>(to the left)</h5></li> -->
              </ul>
            </section>
          </aside>
        <% end %>
      </div>
    </div>
  <div class="col-md-3">
    <%#= render 'communicate_form' %>
  </div>

<% else %>
  <% if false %>
  <div class="jumbotron center">  
    <h1>Welcome to OneDegree</h1>
    <h3> <span class="content">A community where business professionals, entrepreneurs, and other awesome people will help you out. <em>Ask any question. Get advice. Free! Yes Really.</em> </span></h3>

    <%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  
    
    <!--
    <h2>
      This is the home page for the <a href="#">Air Message</a> application.
    </h2>
    -->

    <!--
    <%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-default btn-lg" %>
    -->
  </div>
  <% end %>
  <%= render "pins/index" %>
  <% #= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>
<%#= @user.responder_users.count %>

<%#Commented out the entire code below. Not needed %>
<% if false %>
  <% if user_signed_in? %>
    <% provide(:title, @user.name) %>
    <div class="col-md-8">
      <% if @user.microposts.any? %>
        <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
      <% end %>
    </div>
    <% end %>


  <h1>Listing microposts</h1>

  <table>
    <thead>
      <tr>
        <th>Content</th>
        <th>User</th>
        <th>Initiator</th>
        <th>Responder</th>
        <th>Topic</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @microposts.each do |micropost| %>
        <tr>
          <td><%= micropost.content %></td>
          <td><%= micropost.user_id %></td>
          <td><%= micropost.initiator %></td>
          <td><%= micropost.responder %></td>
          <td><%= micropost.topic %></td>
          <td><%= link_to 'Show', micropost %></td>
          <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
          <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if user_signed_in? %>
    <%= link_to 'New Micropost', new_micropost_path %>
  <% end %>
<% end %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<p>
  <strong>Initiator:</strong>
  <%= @micropost.initiator %>
</p>

<p>
  <strong>Responder:</strong>
  <%= @micropost.responder %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @micropost.topic %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/show_communicate.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%#= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section>
      <%#= render 'pages/stats' %>

      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%#= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
      <%#= @users.count %>
        <%#= render @users %>
          <%= render 'microposts/users' %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>