config/routes.rb
Pinteresting::Application.routes.draw do
  resources :eavesdrops

  resources :microposts

  resources :pins

  devise_for :users
  resources :users do
  member do
      get :whoresponders, :whoinitiators, :conversations
    end
  end

  resources :relationships, only: [:create, :destroy]

  root "microposts#index"
  get "about" => "pages#about"
  get "conversations" => "pins#index"
  get "widgets" => "widgets#ilove"
  get "users_consulting" => "users#consulting_index"
  get "users_gradapplication" => "users#gradapplication_index"
  get "pins_consulting" => "pins#consulting_index"
  get "pins_gradapplication" => "pins#gradapplication_index"

  

end

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48344831-1', '1degree.co');
  ga('send', 'pageview');

</script>

<script src="//static.getclicky.com/js" type="text/javascript"></script>
<script type="text/javascript">try{ clicky.init(100717546); }catch(e){}</script>
<noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/100717546ns.gif" /></p></noscript>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default navbar-background" role="navigation" >
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "OneDegree", root_path, class: "navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">


        <% if user_signed_in? %>
          <li><!--
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span>New Pin
            <% end %> -->
          </li>
          <li><%= link_to "About Us", about_path %></li>
          <!-- <li><%= link_to "Featured Users", "/users#index" %></li>
          <li><%= link_to "Conversations", "/pins#index" %></li> -->
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Featured Users<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li class="dropdown-list"><%= link_to "Consulting", users_consulting_path %></li>
              <li><%= link_to "Graduate Application", users_gradapplication_path %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Conversations<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li class="dropdown-list"><%= link_to "Consulting", pins_consulting_path %></li>
              <li><%= link_to "Graduate Application", pins_gradapplication_path %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">My Stuff<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Account Settings", edit_user_registration_path %></li>
              <li><%= link_to "My Profile", current_user %></li>
              <li><%= link_to "Invite Friends", new_user_invitation_path %></li>
            </ul>
          </li>
          
          <% if false %>
            <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li><%= link_to "Invite Friends", new_user_invitation_path %></li>
          <% end %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete  %></li>
        <% else %>
          <li><%= link_to "About Us", about_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OneDegree</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Lato:400,700' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name,msg| %>
			<%= content_tag(:div,msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
</body>
<%= render 'layouts/footer' %>
</html>